### ISSUE TITLE
The legend has come back.

### ISSUE THREAD

**Issue by Re-gen-web** [pickle69420/pickelhubreact#1]
OMG U were gone 4 so long haha

**Comment by Binary0universe** [comment]
also i stole ur code while you were gone and i was tring to finish it.

**Comment by Binary0universe** [comment]
can you use google cloud cuz its cool

**Comment by neealdon3** [comment]
same

**Comment by pickle69420** [comment]
idk yet i amstill starting to come back it is the second day of school for me
